# -*- coding: utf-8 -*-

"""
    Main window form implementation.

    Ported from the Qt Designer ``base.ui`` generated PyQt4 module to
    PySide6. Widgets now live in ``QtWidgets``.
"""

from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1132, 671)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setWeight(QtGui.QFont.Normal)
        font.setItalic(False)
        font.setBold(False)
        self.centralwidget.setFont(font)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bt_back = QtWidgets.QPushButton(self.frame)
        self.bt_back.setText("")
        self.bt_back.setObjectName("bt_back")
        self.horizontalLayout_5.addWidget(self.bt_back)
        self.bt_ahead = QtWidgets.QPushButton(self.frame)
        self.bt_ahead.setText("")
        self.bt_ahead.setObjectName("bt_ahead")
        self.horizontalLayout_5.addWidget(self.bt_ahead)
        self.bt_reload = QtWidgets.QPushButton(self.frame)
        self.bt_reload.setText("")
        self.bt_reload.setObjectName("bt_reload")
        self.horizontalLayout_5.addWidget(self.bt_reload)
        self.bt_start = QtWidgets.QPushButton(self.frame)
        self.bt_start.setObjectName("bt_start")
        self.horizontalLayout_5.addWidget(self.bt_start)
        self.bt_open = QtWidgets.QPushButton(self.frame)
        self.bt_open.setObjectName("bt_open")
        self.horizontalLayout_5.addWidget(self.bt_open)
        self.bt_save = QtWidgets.QPushButton(self.frame)
        self.bt_save.setObjectName("bt_save")
        self.horizontalLayout_5.addWidget(self.bt_save)
        self.bt_configure = QtWidgets.QPushButton(self.frame)
        self.bt_configure.setObjectName("bt_configure")
        self.horizontalLayout_5.addWidget(self.bt_configure)
        self.bt_settings = QtWidgets.QPushButton(self.frame)
        self.bt_settings.setObjectName("bt_settings")
        self.horizontalLayout_5.addWidget(self.bt_settings)
        self.bt_run = QtWidgets.QPushButton(self.frame)
        self.bt_run.setObjectName("bt_run")
        self.horizontalLayout_5.addWidget(self.bt_run)
        self.tb_url = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_url.sizePolicy().hasHeightForWidth())
        self.tb_url.setSizePolicy(sizePolicy)
        self.tb_url.setSizeIncrement(QtCore.QSize(0, 0))
        self.tb_url.setObjectName("tb_url")
        self.horizontalLayout_5.addWidget(self.tb_url)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.tab_pages = QtWidgets.QTabWidget(self.frame)
        self.tab_pages.setTabsClosable(True)
        self.tab_pages.setMovable(True)
        self.tab_pages.setObjectName("tab_pages")
        self.gridLayout.addWidget(self.tab_pages, 5, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tab_pages.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Crawley Browser"))
        self.bt_start.setText(_translate("MainWindow", "Start Project"))
        self.bt_open.setText(_translate("MainWindow", "Open Project"))
        self.bt_save.setText(_translate("MainWindow", "Save"))
        self.bt_configure.setText(_translate("MainWindow", "Configure"))
        self.bt_settings.setText(_translate("MainWindow", "Settings"))
        self.bt_run.setText(_translate("MainWindow", "Run Crawler"))
