# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Mon Oct 24 23:38:01 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(340, 476)
        self.groupBox = QtGui.QGroupBox(Settings)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 541, 241))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 30, 311, 202))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(-1, 0, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.cb_engine = QtGui.QComboBox(self.formLayoutWidget)
        self.cb_engine.setObjectName("cb_engine")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cb_engine)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.tb_name = QtGui.QLineEdit(self.formLayoutWidget)
        self.tb_name.setObjectName("tb_name")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.tb_name)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.tb_user = QtGui.QLineEdit(self.formLayoutWidget)
        self.tb_user.setObjectName("tb_user")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.tb_user)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.tb_password = QtGui.QLineEdit(self.formLayoutWidget)
        self.tb_password.setObjectName("tb_password")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.tb_password)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.tb_host = QtGui.QLineEdit(self.formLayoutWidget)
        self.tb_host.setObjectName("tb_host")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.tb_host)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.tb_port = QtGui.QLineEdit(self.formLayoutWidget)
        self.tb_port.setObjectName("tb_port")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.tb_port)
        self.groupBox_2 = QtGui.QGroupBox(Settings)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 250, 491, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 311, 71))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.tb_xml = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.tb_xml.setObjectName("tb_xml")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.tb_xml)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.tb_json = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.tb_json.setObjectName("tb_json")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.tb_json)
        self.groupBox_3 = QtGui.QGroupBox(Settings)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 360, 301, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 30, 301, 41))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.ck_show_debug = QtGui.QCheckBox(self.formLayoutWidget_3)
        self.ck_show_debug.setObjectName("ck_show_debug")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.ck_show_debug)
        self.bt_ok = QtGui.QPushButton(Settings)
        self.bt_ok.setGeometry(QtCore.QRect(227, 440, 91, 27))
        self.bt_ok.setObjectName("bt_ok")
        self.bt_cancel = QtGui.QPushButton(Settings)
        self.bt_cancel.setGeometry(QtCore.QRect(130, 440, 91, 27))
        self.bt_cancel.setObjectName("bt_cancel")

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QtGui.QApplication.translate("Settings", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Settings", "DataBase Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Settings", "Engine", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Settings", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Settings", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Settings", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Settings", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Settings", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Settings", "Documents Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Settings", "XML Doc.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Settings", "Json Doc.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Settings", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.ck_show_debug.setText(QtGui.QApplication.translate("Settings", "Show Debug Info", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_ok.setText(QtGui.QApplication.translate("Settings", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_cancel.setText(QtGui.QApplication.translate("Settings", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

