# -*- coding: utf-8 -*-

"""
    Project settings dialog form implementation.

    Ported from the Qt Designer ``settings.ui`` generated PyQt4 module to
    PySide6. Widgets now live in ``QtWidgets``.
"""

from PySide6 import QtCore, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(340, 476)
        self.groupBox = QtWidgets.QGroupBox(Settings)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 541, 241))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 30, 311, 202))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(-1, 0, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cb_engine = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_engine.setObjectName("cb_engine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_engine)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.tb_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.tb_name.setObjectName("tb_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tb_name)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.tb_user = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.tb_user.setObjectName("tb_user")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tb_user)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.tb_password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.tb_password.setObjectName("tb_password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tb_password)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.tb_host = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.tb_host.setObjectName("tb_host")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tb_host)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.tb_port = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.tb_port.setObjectName("tb_port")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tb_port)
        self.groupBox_2 = QtWidgets.QGroupBox(Settings)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 250, 491, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 311, 71))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.tb_xml = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.tb_xml.setObjectName("tb_xml")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tb_xml)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.tb_json = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.tb_json.setObjectName("tb_json")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tb_json)
        self.groupBox_3 = QtWidgets.QGroupBox(Settings)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 360, 301, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 30, 301, 41))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.ck_show_debug = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.ck_show_debug.setObjectName("ck_show_debug")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ck_show_debug)
        self.bt_ok = QtWidgets.QPushButton(Settings)
        self.bt_ok.setGeometry(QtCore.QRect(227, 440, 91, 27))
        self.bt_ok.setObjectName("bt_ok")
        self.bt_cancel = QtWidgets.QPushButton(Settings)
        self.bt_cancel.setGeometry(QtCore.QRect(130, 440, 91, 27))
        self.bt_cancel.setObjectName("bt_cancel")

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.groupBox.setTitle(_translate("Settings", "DataBase Settings"))
        self.label.setText(_translate("Settings", "Engine"))
        self.label_2.setText(_translate("Settings", "Name"))
        self.label_3.setText(_translate("Settings", "User"))
        self.label_4.setText(_translate("Settings", "Password"))
        self.label_5.setText(_translate("Settings", "Host"))
        self.label_6.setText(_translate("Settings", "Port"))
        self.groupBox_2.setTitle(_translate("Settings", "Documents Settings"))
        self.label_8.setText(_translate("Settings", "XML Doc."))
        self.label_9.setText(_translate("Settings", "Json Doc."))
        self.groupBox_3.setTitle(_translate("Settings", "General"))
        self.ck_show_debug.setText(_translate("Settings", "Show Debug Info"))
        self.bt_ok.setText(_translate("Settings", "Ok"))
        self.bt_cancel.setText(_translate("Settings", "Cancel"))
